### ISSUE TITLE
[MSY2 MINGW64] Styles structures are problematic

### ISSUE THREAD

**Issue by iahung** [dacap/vaca#10]
These structures are not properly exposed and not accessible either with shared or static version of the library:

`vaca::Widget::Styles::`
`vaca::Frame::Styles::`
`vaca::MdiClient::Styles::`
`vaca::TextEdit::Styles::`
`vaca::SplitBar::Styles::`
`vaca::TreeView::Styles::`

The use of `constexpr` maybe the problem.

Update: it's very likely that `constexpr` is causing the problem, a quick Google searched showed `constexpr` doesn't work with `__declspec(dllexport)` and `__declspec(dllimport)`. Strangely enough, these structures are not exposed and accessible on the static version of the library too.

**Comment by dacap** [comment]
[Fixed removing the VACA_DLL](https://github.com/dacap/vaca/commit/602604b5a3976302148738e47f420027b6d5f26a) (dllimport/export) to the Styles struct. It looks like a new issue with MinGW introduced after changing the Styles to constexpr.

Now vaca is compiled correctly with msvc/mingw/msys/clang: https://github.com/dacap/vaca/actions/runs/4674104463
