### ISSUE TITLE
cmake is the reason this project is not more popular...

### ISSUE THREAD

**Issue by Athlon1600** [dacap/vaca#2]
You must be the only person who managed to actually compile this project... only cmake can turn a simple task of just compiling it all into one .lib file and making it so complicated my god

**Comment by dacap** [comment]
Hi @Athlon1600, I would like to help you, did you try the installation instructions from [INSTALL.txt](https://github.com/dacap/vaca/blob/master/INSTALL.txt)? Are you using Visual Studio or MinGW?

About the project popularity, this library was (and is) experimental, so I prefer to keep it in a low profile.

**Comment by Athlon1600** [comment]
I have them both. Cmake just creates a thousand files and all of them useless. I don't see why Cmake exists at all. How is it at all better and easier than a regular bash script? What would be the exact gcc command to put all those vaca/*.cpp files into one lib file?

I have yet to see a more complete win32 gui wrapper that doesn't involve Boost or that doesn't try to be cross-platform.

**Comment by dacap** [comment]
> I don't see why Cmake exists at all.

:astonished: when you develop any kind of C++ project, the first thing you need to pick is a build system. You can use Visual Studio solutions, Makefiles, bat/bash scripts, or whatever you want. I chose cmake, which is a pretty common build system for C++ projects (also it generates nmake makefiles, ninja makefiles, and Visual Studio 2005/2008/2010/2012/2013 solutions, a lot of possibilities  that you cannot maintain manually).

Remember that Vaca includes a lot of examples and unit tests. It's not just a .lib file.

> How is it at all better and easier than a regular bash script?

:astonished: (x2) I would like to ask how is that a bash script makes sense on the Windows platform for you? Bash isn't something expected on Windows (e.g. people that use Visual Studio) and a .bat script is out of discussion.

> What would be the exact gcc command to put all those vaca/*.cpp files into one lib file?

Use cmake to create the make or nmake files. Then see the command lines in those makefiles.

> I have yet to see a more complete win32 gui wrapper that doesn't involve Boost or that doesn't try to be cross-platform.

Vaca is not portable, it's only for Windows, and doesn't depend on Boost. But my question is, if you cannot even dedicate enough time to compile a library, do you really want to use it?

Also remember that this project is experimental, you can use for test projects, or minimal applications, but doesn't expect that things will be work.

Also I think that the [last tag](https://github.com/dacap/vaca/tree/v0.0.7) has makefiles (nmake and GNU makefiles), but I'm not sure. Maybe you could give a try to it.
