### ISSUE TITLE
CMakeLists.txt : target_compile_features no longer work as expected

### ISSUE THREAD

**Issue by ghost** [dacap/vaca#9]
`target_compile_features(vaca PUBLIC cxx_std_14)` will no longer work as you expected. When you wrote this line C++14 was the latest, but now it's C++17 or even C++20. For example, the GCC 12.2.0 compiler of MSYS2 MINGW64 targets C++17 by default. Since C++17 is greater than C++14 and `cxx_std_14` means at least C++14 so `-std=c++14` will not be added and it will default to C++17. There will be warning about the `register` keyword is not allowed on C++17.

https://cmake.org/cmake/help/latest/command/target_compile_features.html

The solution as the document said is explicitly forcing C++14 with:

```
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD 14)
```

The `target_compile_features` line could be removed.

**Comment by dacap** [comment]
Actually I'm used to CMAKE_CXX_STANDARD  and CMAKE_CXX_STANDARD_REQUIRED in other of my libraries ([clip](https://github.com/dacap/clip/blob/4adde2472bea295ab940e180f427f686da2d6e2e/CMakeLists.txt#L8)) but I'm not sure why I used target_compile_features() here.

Anyway [removing the usage of the old `register` keyword](https://github.com/dacap/vaca/commit/205b68ae07ad656e6461ee702fd927543b286eb0) fixed some issues related to this.
